import json
import logging
from pathlib import Path
from typing import Dict, List, Any

from multiqc.base_module import BaseMultiqcModule, ModuleNoSamplesFound
from multiqc.plots import table

log = logging.getLogger(__name__)


class MultiqcModule(BaseMultiqcModule):
    """
    Celescope module for parsing .data.json files from Celescope pipeline.

    This module parses JSON summary files generated by Celescope, a single-cell
     analysis pipeline. It extracts metrics from various pipeline steps
    and presents them in organized tables.

    The input files are .data.json files containing structured summary data.
    Sample names are extracted from the "Sample ID" field in sample_summary.
    """

    def __init__(self):
        super(MultiqcModule, self).__init__(
            name="Celescope",
            anchor="celescope",
            href="https://github.com/singleron-RD/CeleScope",
            info="Single-cell analysis pipeline metrics.",
        )

        # Find and parse .data.json files
        self.celescope_data: Dict[str, Dict[str, Any]] = dict()

        # Search for .data.json files
        for f in self.find_log_files("celescope/data_json"):
            self.parse_data_json(f)

        # Filter to strip out ignored sample names
        self.celescope_data = self.ignore_samples(self.celescope_data)

        if len(self.celescope_data) == 0:
            raise ModuleNoSamplesFound

        log.info(f"Found {len(self.celescope_data)} Celescope reports")

        # Parse and add sections for each step
        self.parse_sections()

        # Write parsed data to file
        self.write_data_file(self.celescope_data, "multiqc_celescope")

    def parse_data_json(self, f):
        """Parse a single .data.json file."""
        try:
            data = json.loads(f["f"])
        except json.JSONDecodeError as e:
            log.warning(f"Could not parse Celescope JSON file {f['fn']}: {e}")
            return

        # extract assay
        try:
            sample_metric = data["sample_summary"]["metric_list"]
        except: 
            log.warning(f"Could not find metric_list in sample_summary for {f['fn']}")
            return 
        
        sample_name, assay = None, None
        for metric in sample_metric:
            if metric.get("name") == "Assay":
                assay = metric.get("value")
            elif metric.get("name") == "Sample ID":
                sample_name = metric.get("value")

        if not (sample_name and assay):
            log.warning(f"Could not find Sample ID or Assay in {f['fn']}")
            return

        # Clean sample name
        sample_name = self.clean_s_name(sample_name, f)

        if sample_name in self.celescope_data:
            log.debug(f"Duplicate sample name found! Overwriting: {sample_name}")

        # Store the parsed data
        self.celescope_data[sample_name] = data
        self.celescope_data[sample_name]["assay"] = assay
        self.celescope_data[sample_name]["data_source"] = f["fn"]
        self.celescope_data[sample_name]["_file_dict"] = f

        # ada source
        self.add_data_source(f, sample_name, module=f'celescope-{assay}', section=assay)

    def parse_sections(self):
        """Parse and create sections for each step that has metrics."""
        # Collect all step names across all samples
        all_steps = set()
        for sample_data in self.celescope_data.values():
            for key in sample_data.keys():
                if key.endswith("_summary") and "metric_list" in sample_data[key]:
                    step_name = key.replace("_summary", "")
                    all_steps.add(step_name)

        # sort all steps
        order = ["sample", "demultiplexing", "mapping", "cells", "analysis"]
        weight = {k: i for i, k in enumerate(order)}
        all_steps = list(all_steps)
        all_steps.sort(key=lambda x: weight.get(x, len(order)))

        color_schemes = ['GnBu', 'RdYlGn', 'PuBu', 'YlOrRd', 'Spectral']

        # Create sections for each step
        for step in all_steps:
            step_key = f"{step}_summary"
            step_data = {}

            # Collect data for this step across all samples
            headers = {}
            for s_name, sample_data in self.celescope_data.items():
                if step_key in sample_data and sample_data[step_key]["metric_list"]:
                    step_data[s_name] = {}

                    for i, metric in enumerate(sample_data[step_key]["metric_list"]):
                        if not metric.get("show", True):
                            continue

                        metric_name = metric["name"]
                        value = metric.get("value")
                        display = metric.get("display")
                        help_text = metric.get("help_info")

                        # analysis mito fix
                        if isinstance(value, str) and value.endswith("%"):
                            value = float(value.rstrip("%"))
                        step_data[s_name][metric_name] = value

                        # Set up headers
                        if metric_name not in headers:
                            headers[metric_name] = {
                                "title": metric_name,
                                "description": help_text or "",
                                "scale": color_schemes[i % len(color_schemes)],
                            }

                            if display.endswith("%"):
                                headers[metric_name]["suffix"] = "%"

                            if metric_name == 'Chemistry':
                                headers[metric_name]["description"] = ""

                            if metric_name == 'Sample ID':
                                headers.pop(metric_name)



            # Only create section if we have data
            if step_data:
                # Capitalize first letter of step name for display
                display_name = step.replace("_", " ").title()

                self.add_section(
                    name=display_name,
                    anchor=f"celescope_{step}",
                    description=f"Metrics from the {display_name} step of the Celescope pipeline.",
                    plot=table.plot(step_data, headers, pconfig={
                        "id": f"celescope_{step}_table",
                        "title": f"Celescope: {display_name}",
                    })
                )